---
title: "HW3_SM"
format: html
editor: visual
---

# Task 1: Conceptual Questions

1.  If your working directory is **myfolder/homework/**, what *relative* path would you specify to get the file located at **myfolder/MyData.csv**?
* "../MyData.csv"

2.  What are the major benefits of using R projects?
* Allows for the creation of a file hierarchy when working on one project that contains multiple files
* It's association with a directory allows for ease in sharing/ collaborating
* R projects can be connected with Git and GitHub to allow for version control and collaboration

3.  What is **Git** and what is **GitHub**?
* Git: a software that allows for version tracking of different projects.
* GitHub: an online hosting service for Git projects that allows for storage and sharing of these projects.

4.  What are the two main differences between a **tibble** and a **data.frame**?
* A tibble is a type of data frame that is specific to the tidy verse package. A data frame cannot exist in the tidyverse if it's not a tibble.
* When a tibble is printed, we get information about the number of observations and see an output of the first few columns. When a data frame is printed, the output is generally the entire data frame regardless of the number of observations.

# Task 2: Reading Delimited Data

# Task 3: Combining Excel and Delimited Data

# Task 4: Writing a Function
